import { type Filesystem, type FStat } from "@ncpa0cpl/fs-explorer";
import { lookup } from "mrmime";
import type { DirEntry } from "../shared/fs-types";
import type { Platform } from "../shared/platform/types";
import { generateCanvasThumbnail } from "./media-thumbs";

/**
 * Implementation of fs-explorer's `Filesystem` interface on top of the
 * `window.xplorer` IPC bridge.
 *
 * Built per platform via `createFilesystem(platform)`: all path joins and
 * the hidden-file rule come from the shared `Platform`, so POSIX and win32
 * path shapes are produced consistently. Correctness note: main's
 * `fs:readdirStat` handler returns real Node paths only in the form of
 * (directory, entry-name) pairs - this adapter is the single place that
 * derives full entry paths, always via `platform.paths.join(dirpath, name)`,
 * so the string the renderer circulates is exactly what main's own
 * node:path-based handlers accept back on the next IPC call.
 */

const xplorer = window.xplorer;

/** Builds the IPC-backed `Filesystem` for the given platform. */
export function createFilesystem(platform: Platform): Filesystem {
  return {
    readdir(p) {
      return readdirStat(p).then((entries) => entries.map((e) => e.name));
    },

    // Batched: a single IPC round trip fetches the dir listing with full stats,
    // real read/write flags and mime detection for every entry.
    readdirStat(dirpath) {
      return xplorer.readdirStat(dirpath).then((entries) =>
        entries.map((entry) => entryToFStat(platform, dirpath, entry))
      );
    },

    async stat(filepath) {
      const entry = await xplorer.stat(filepath);
      return entryToFStat(platform, platform.paths.dirname(filepath), entry);
    },

    copy(from, to) {
      return xplorer.copy(from, to);
    },

    move(from, to) {
      return xplorer.move(from, to);
    },

    // Product decision: "delete" moves files to the OS trash rather than
    // permanently removing them. The lib never calls `remove()` as part of its
    // overwrite flow (it only prompts, then expects copy/move to overwrite), so
    // trashing here is safe.
    remove(p) {
      return xplorer.trash(p);
    },

    mkdir(p) {
      return xplorer.mkdir(p);
    },

    touch(p) {
      return xplorer.touch(p);
    },

    exists(p) {
      return xplorer.exists(p);
    },

    dirExists(p) {
      return xplorer.dirExists(p);
    },

    dirSize(dirpath) {
      return readdirStat(dirpath).then((entries) =>
        entries.reduce(
          (sum, entry) => entry.isDirectory ? sum : sum + entry.size,
          0,
        )
      );
    },

    // ─── File-change watching ────────────────────────────────────────────────
    //
    // Main keeps one non-recursive `fs.watch` per browsed directory (seeded by
    // the `fs:readdirStat` handler, so every dir a tab visits is watched) and
    // pushes `fs:change` events over IPC. The lib registers one global
    // `(dirPath?: string) => void` callback at startup (explorer.ts) and calls
    // `tab.refresh(dirPath)` on every tab; `dirPath` must equal the directory
    // path exactly as the tab browsed it — `history.findEntry` compares via
    // `Path.equals`, a normalized *segment-wise* comparison — so we forward
    // main's `dirPath` verbatim (it is the exact string main received from
    // `readdirStat`, i.e. the same string the renderer passes around). The
    // callback set and bridge subscription live at module scope below.

    onChange(callback) {
      ensureBridgeSubscription();
      changeCallbacks.add(callback);
    },

    offChange(callback) {
      changeCallbacks.delete(callback);
    },

    // ─── Thumbnails (disk-cached, streaming URLs) ────────────────────────────
    //
    // Main process first: a small PNG generated by nativeImage and persisted in
    // `userData/thumbnails` (served back as an `xmedia://` URL). On a miss the
    // renderer generates the thumbnail with a canvas (videos, GIF/WebP/AVIF/SVG)
    // and pushes it to the main process's disk cache via `media:cacheThumbnail`,
    // so it is generated only once per file version.

    async thumbnail(p) {
      try {
        const cached = await xplorer.getThumbnail(p);
        if (cached) return cached;

        const dataUrl = await generateCanvasThumbnail(p);
        if (!dataUrl) return null;
        const persisted = await xplorer.cacheThumbnail(p, dataUrl).catch(() =>
          ""
        );
        return persisted || dataUrl;
      } catch {
        return null;
      }
    },
  };
}

// ─── File-change watching plumbing ───────────────────────────────────────────

const changeCallbacks = new Set<(dirPath?: string) => void>();

// Single bridge subscription, created lazily on first onChange registration;
// it lives for the page lifetime (the lib itself registers one callback for
// the Explorer's lifetime and unsubscribes on Explorer destroy).
let bridgeSubscribed = false;
function ensureBridgeSubscription(): void {
  if (bridgeSubscribed) return;
  bridgeSubscribed = true;
  xplorer.onFsChange((event) => {
    // Copy so callbacks may unsubscribe during iteration; a throwing
    // callback must not break the others.
    for (const cb of [...changeCallbacks]) {
      try {
        cb(event.dirPath);
      } catch {
        // Ignore listener errors.
      }
    }
  });
}

function readdirStat(dirpath: string): Promise<DirEntry[]> {
  return xplorer.readdirStat(dirpath);
}

function entryToFStat(
  platform: Platform,
  dirpath: string,
  entry: DirEntry,
): FStat {
  return {
    basedir: dirpath,
    directory: entry.isDirectory,
    name: entry.name,
    // Platform-specific hiding convention: leading dot on POSIX, the
    // documented name-based approximation on win32.
    hidden: platform.files.isHiddenName(entry.name),
    path: platform.paths.join(dirpath, entry.name),
    read: entry.readable,
    write: entry.writable,
    size: entry.size,
    mtime: entry.mtimeMs / 1000,
    ctime: entry.ctimeMs / 1000,
    atime: entry.atimeMs / 1000,
    mimetype: entry.isDirectory ? undefined : lookup(entry.name),
  };
}
